//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/pod_network.proto

package networking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodNetwork_GetPodResources_FullMethodName = "/dranet.networking.v1.PodNetwork/GetPodResources"
	PodNetwork_GetPodIPs_FullMethodName       = "/dranet.networking.v1.PodNetwork/GetPodIPs"
	PodNetwork_GetPodNetwork_FullMethodName   = "/dranet.networking.v1.PodNetwork/GetPodNetwork"
	PodNetwork_MoveDevice_FullMethodName      = "/dranet.networking.v1.PodNetwork/MoveDevice"
	PodNetwork_AssignIPAddress_FullMethodName = "/dranet.networking.v1.PodNetwork/AssignIPAddress"
	PodNetwork_ApplyRoute_FullMethodName      = "/dranet.networking.v1.PodNetwork/ApplyRoute"
	PodNetwork_ApplyRule_FullMethodName       = "/dranet.networking.v1.PodNetwork/ApplyRule"
	PodNetwork_CreateNetdev_FullMethodName    = "/dranet.networking.v1.PodNetwork/CreateNetdev"
)

// PodNetworkClient is the client API for PodNetwork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PodNetwork provides an API for managing pod-level network resources.
type PodNetworkClient interface {
	// GetPodResources returns resources associated with a pod sandbox.
	GetPodResources(ctx context.Context, in *GetPodResourcesRequest, opts ...grpc.CallOption) (*GetPodResourcesResponse, error)
	// GetPodIPs returns the IP addresses assigned to a pod sandbox.
	GetPodIPs(ctx context.Context, in *GetPodIPsRequest, opts ...grpc.CallOption) (*GetPodIPsResponse, error)
	// GetPodNetwork returns the full network state of a pod sandbox,
	// including all interfaces, IP addresses, routes, and routing rules.
	GetPodNetwork(ctx context.Context, in *GetPodNetworkRequest, opts ...grpc.CallOption) (*GetPodNetworkResponse, error)
	// MoveDevice moves a network device (netdev or RDMA) from the root
	// network namespace into the pod sandbox's network namespace. Any IP
	// addresses, routes, and routing rules associated with the device in
	// the root namespace are preserved and applied in the target namespace.
	MoveDevice(ctx context.Context, in *MoveDeviceRequest, opts ...grpc.CallOption) (*MoveDeviceResponse, error)
	// AssignIPAddress assigns an IP address to an interface within the
	// pod sandbox's network namespace.
	AssignIPAddress(ctx context.Context, in *AssignIPAddressRequest, opts ...grpc.CallOption) (*AssignIPAddressResponse, error)
	// ApplyRoute adds a route in the pod sandbox's network namespace.
	ApplyRoute(ctx context.Context, in *ApplyRouteRequest, opts ...grpc.CallOption) (*ApplyRouteResponse, error)
	// ApplyRule adds an ip rule in the pod sandbox's network namespace.
	ApplyRule(ctx context.Context, in *ApplyRuleRequest, opts ...grpc.CallOption) (*ApplyRuleResponse, error)
	// CreateNetdev creates a new Linux network device inside the pod
	// sandbox's network namespace. Supports veth, vxlan, dummy, ipvlan,
	// and macvlan device types.
	CreateNetdev(ctx context.Context, in *CreateNetdevRequest, opts ...grpc.CallOption) (*CreateNetdevResponse, error)
}

type podNetworkClient struct {
	cc grpc.ClientConnInterface
}

func NewPodNetworkClient(cc grpc.ClientConnInterface) PodNetworkClient {
	return &podNetworkClient{cc}
}

func (c *podNetworkClient) GetPodResources(ctx context.Context, in *GetPodResourcesRequest, opts ...grpc.CallOption) (*GetPodResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodResourcesResponse)
	err := c.cc.Invoke(ctx, PodNetwork_GetPodResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) GetPodIPs(ctx context.Context, in *GetPodIPsRequest, opts ...grpc.CallOption) (*GetPodIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodIPsResponse)
	err := c.cc.Invoke(ctx, PodNetwork_GetPodIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) GetPodNetwork(ctx context.Context, in *GetPodNetworkRequest, opts ...grpc.CallOption) (*GetPodNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodNetworkResponse)
	err := c.cc.Invoke(ctx, PodNetwork_GetPodNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) MoveDevice(ctx context.Context, in *MoveDeviceRequest, opts ...grpc.CallOption) (*MoveDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveDeviceResponse)
	err := c.cc.Invoke(ctx, PodNetwork_MoveDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) AssignIPAddress(ctx context.Context, in *AssignIPAddressRequest, opts ...grpc.CallOption) (*AssignIPAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignIPAddressResponse)
	err := c.cc.Invoke(ctx, PodNetwork_AssignIPAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) ApplyRoute(ctx context.Context, in *ApplyRouteRequest, opts ...grpc.CallOption) (*ApplyRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyRouteResponse)
	err := c.cc.Invoke(ctx, PodNetwork_ApplyRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) ApplyRule(ctx context.Context, in *ApplyRuleRequest, opts ...grpc.CallOption) (*ApplyRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyRuleResponse)
	err := c.cc.Invoke(ctx, PodNetwork_ApplyRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podNetworkClient) CreateNetdev(ctx context.Context, in *CreateNetdevRequest, opts ...grpc.CallOption) (*CreateNetdevResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNetdevResponse)
	err := c.cc.Invoke(ctx, PodNetwork_CreateNetdev_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodNetworkServer is the server API for PodNetwork service.
// All implementations must embed UnimplementedPodNetworkServer
// for forward compatibility.
//
// PodNetwork provides an API for managing pod-level network resources.
type PodNetworkServer interface {
	// GetPodResources returns resources associated with a pod sandbox.
	GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error)
	// GetPodIPs returns the IP addresses assigned to a pod sandbox.
	GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error)
	// GetPodNetwork returns the full network state of a pod sandbox,
	// including all interfaces, IP addresses, routes, and routing rules.
	GetPodNetwork(context.Context, *GetPodNetworkRequest) (*GetPodNetworkResponse, error)
	// MoveDevice moves a network device (netdev or RDMA) from the root
	// network namespace into the pod sandbox's network namespace. Any IP
	// addresses, routes, and routing rules associated with the device in
	// the root namespace are preserved and applied in the target namespace.
	MoveDevice(context.Context, *MoveDeviceRequest) (*MoveDeviceResponse, error)
	// AssignIPAddress assigns an IP address to an interface within the
	// pod sandbox's network namespace.
	AssignIPAddress(context.Context, *AssignIPAddressRequest) (*AssignIPAddressResponse, error)
	// ApplyRoute adds a route in the pod sandbox's network namespace.
	ApplyRoute(context.Context, *ApplyRouteRequest) (*ApplyRouteResponse, error)
	// ApplyRule adds an ip rule in the pod sandbox's network namespace.
	ApplyRule(context.Context, *ApplyRuleRequest) (*ApplyRuleResponse, error)
	// CreateNetdev creates a new Linux network device inside the pod
	// sandbox's network namespace. Supports veth, vxlan, dummy, ipvlan,
	// and macvlan device types.
	CreateNetdev(context.Context, *CreateNetdevRequest) (*CreateNetdevResponse, error)
	mustEmbedUnimplementedPodNetworkServer()
}

// UnimplementedPodNetworkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodNetworkServer struct{}

func (UnimplementedPodNetworkServer) GetPodResources(context.Context, *GetPodResourcesRequest) (*GetPodResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPodResources not implemented")
}
func (UnimplementedPodNetworkServer) GetPodIPs(context.Context, *GetPodIPsRequest) (*GetPodIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPodIPs not implemented")
}
func (UnimplementedPodNetworkServer) GetPodNetwork(context.Context, *GetPodNetworkRequest) (*GetPodNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPodNetwork not implemented")
}
func (UnimplementedPodNetworkServer) MoveDevice(context.Context, *MoveDeviceRequest) (*MoveDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveDevice not implemented")
}
func (UnimplementedPodNetworkServer) AssignIPAddress(context.Context, *AssignIPAddressRequest) (*AssignIPAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignIPAddress not implemented")
}
func (UnimplementedPodNetworkServer) ApplyRoute(context.Context, *ApplyRouteRequest) (*ApplyRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyRoute not implemented")
}
func (UnimplementedPodNetworkServer) ApplyRule(context.Context, *ApplyRuleRequest) (*ApplyRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyRule not implemented")
}
func (UnimplementedPodNetworkServer) CreateNetdev(context.Context, *CreateNetdevRequest) (*CreateNetdevResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetdev not implemented")
}
func (UnimplementedPodNetworkServer) mustEmbedUnimplementedPodNetworkServer() {}
func (UnimplementedPodNetworkServer) testEmbeddedByValue()                    {}

// UnsafePodNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodNetworkServer will
// result in compilation errors.
type UnsafePodNetworkServer interface {
	mustEmbedUnimplementedPodNetworkServer()
}

func RegisterPodNetworkServer(s grpc.ServiceRegistrar, srv PodNetworkServer) {
	// If the following call panics, it indicates UnimplementedPodNetworkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodNetwork_ServiceDesc, srv)
}

func _PodNetwork_GetPodResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).GetPodResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_GetPodResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).GetPodResources(ctx, req.(*GetPodResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_GetPodIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).GetPodIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_GetPodIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).GetPodIPs(ctx, req.(*GetPodIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_GetPodNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).GetPodNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_GetPodNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).GetPodNetwork(ctx, req.(*GetPodNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_MoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).MoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_MoveDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).MoveDevice(ctx, req.(*MoveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_AssignIPAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignIPAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).AssignIPAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_AssignIPAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).AssignIPAddress(ctx, req.(*AssignIPAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_ApplyRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).ApplyRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_ApplyRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).ApplyRoute(ctx, req.(*ApplyRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_ApplyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).ApplyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_ApplyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).ApplyRule(ctx, req.(*ApplyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodNetwork_CreateNetdev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetdevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNetworkServer).CreateNetdev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodNetwork_CreateNetdev_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNetworkServer).CreateNetdev(ctx, req.(*CreateNetdevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodNetwork_ServiceDesc is the grpc.ServiceDesc for PodNetwork service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodNetwork_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dranet.networking.v1.PodNetwork",
	HandlerType: (*PodNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPodResources",
			Handler:    _PodNetwork_GetPodResources_Handler,
		},
		{
			MethodName: "GetPodIPs",
			Handler:    _PodNetwork_GetPodIPs_Handler,
		},
		{
			MethodName: "GetPodNetwork",
			Handler:    _PodNetwork_GetPodNetwork_Handler,
		},
		{
			MethodName: "MoveDevice",
			Handler:    _PodNetwork_MoveDevice_Handler,
		},
		{
			MethodName: "AssignIPAddress",
			Handler:    _PodNetwork_AssignIPAddress_Handler,
		},
		{
			MethodName: "ApplyRoute",
			Handler:    _PodNetwork_ApplyRoute_Handler,
		},
		{
			MethodName: "ApplyRule",
			Handler:    _PodNetwork_ApplyRule_Handler,
		},
		{
			MethodName: "CreateNetdev",
			Handler:    _PodNetwork_CreateNetdev_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pod_network.proto",
}
