//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/pod_network.proto

package networking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceType indicates the kind of device to move into the pod netns.
type DeviceType int32

const (
	DeviceType_NETDEV DeviceType = 0
	DeviceType_RDMA   DeviceType = 1
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "NETDEV",
		1: "RDMA",
	}
	DeviceType_value = map[string]int32{
		"NETDEV": 0,
		"RDMA":   1,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pod_network_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_proto_pod_network_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{0}
}

// MacvlanMode selects the forwarding behavior for macvlan devices.
type MacvlanMode int32

const (
	MacvlanMode_MACVLAN_BRIDGE   MacvlanMode = 0
	MacvlanMode_MACVLAN_VEPA     MacvlanMode = 1
	MacvlanMode_MACVLAN_PRIVATE  MacvlanMode = 2
	MacvlanMode_MACVLAN_PASSTHRU MacvlanMode = 3
	MacvlanMode_MACVLAN_SOURCE   MacvlanMode = 4
)

// Enum value maps for MacvlanMode.
var (
	MacvlanMode_name = map[int32]string{
		0: "MACVLAN_BRIDGE",
		1: "MACVLAN_VEPA",
		2: "MACVLAN_PRIVATE",
		3: "MACVLAN_PASSTHRU",
		4: "MACVLAN_SOURCE",
	}
	MacvlanMode_value = map[string]int32{
		"MACVLAN_BRIDGE":   0,
		"MACVLAN_VEPA":     1,
		"MACVLAN_PRIVATE":  2,
		"MACVLAN_PASSTHRU": 3,
		"MACVLAN_SOURCE":   4,
	}
)

func (x MacvlanMode) Enum() *MacvlanMode {
	p := new(MacvlanMode)
	*p = x
	return p
}

func (x MacvlanMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MacvlanMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pod_network_proto_enumTypes[1].Descriptor()
}

func (MacvlanMode) Type() protoreflect.EnumType {
	return &file_proto_pod_network_proto_enumTypes[1]
}

func (x MacvlanMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MacvlanMode.Descriptor instead.
func (MacvlanMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{1}
}

// IpvlanMode selects the forwarding behavior for ipvlan devices.
type IpvlanMode int32

const (
	IpvlanMode_IPVLAN_L2  IpvlanMode = 0
	IpvlanMode_IPVLAN_L3  IpvlanMode = 1
	IpvlanMode_IPVLAN_L3S IpvlanMode = 2
)

// Enum value maps for IpvlanMode.
var (
	IpvlanMode_name = map[int32]string{
		0: "IPVLAN_L2",
		1: "IPVLAN_L3",
		2: "IPVLAN_L3S",
	}
	IpvlanMode_value = map[string]int32{
		"IPVLAN_L2":  0,
		"IPVLAN_L3":  1,
		"IPVLAN_L3S": 2,
	}
)

func (x IpvlanMode) Enum() *IpvlanMode {
	p := new(IpvlanMode)
	*p = x
	return p
}

func (x IpvlanMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpvlanMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pod_network_proto_enumTypes[2].Descriptor()
}

func (IpvlanMode) Type() protoreflect.EnumType {
	return &file_proto_pod_network_proto_enumTypes[2]
}

func (x IpvlanMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpvlanMode.Descriptor instead.
func (IpvlanMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{2}
}

// IpvlanFlag selects the isolation mode for ipvlan devices.
type IpvlanFlag int32

const (
	IpvlanFlag_IPVLAN_FLAG_BRIDGE  IpvlanFlag = 0
	IpvlanFlag_IPVLAN_FLAG_PRIVATE IpvlanFlag = 1
	IpvlanFlag_IPVLAN_FLAG_VEPA    IpvlanFlag = 2
)

// Enum value maps for IpvlanFlag.
var (
	IpvlanFlag_name = map[int32]string{
		0: "IPVLAN_FLAG_BRIDGE",
		1: "IPVLAN_FLAG_PRIVATE",
		2: "IPVLAN_FLAG_VEPA",
	}
	IpvlanFlag_value = map[string]int32{
		"IPVLAN_FLAG_BRIDGE":  0,
		"IPVLAN_FLAG_PRIVATE": 1,
		"IPVLAN_FLAG_VEPA":    2,
	}
)

func (x IpvlanFlag) Enum() *IpvlanFlag {
	p := new(IpvlanFlag)
	*p = x
	return p
}

func (x IpvlanFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpvlanFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pod_network_proto_enumTypes[3].Descriptor()
}

func (IpvlanFlag) Type() protoreflect.EnumType {
	return &file_proto_pod_network_proto_enumTypes[3]
}

func (x IpvlanFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpvlanFlag.Descriptor instead.
func (IpvlanFlag) EnumDescriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{3}
}

type GetPodResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodResourcesRequest) Reset() {
	*x = GetPodResourcesRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodResourcesRequest) ProtoMessage() {}

func (x *GetPodResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetPodResourcesRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{0}
}

func (x *GetPodResourcesRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetPodResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodNetnsPath  string                 `protobuf:"bytes,1,opt,name=pod_netns_path,json=podNetnsPath,proto3" json:"pod_netns_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodResourcesResponse) Reset() {
	*x = GetPodResourcesResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodResourcesResponse) ProtoMessage() {}

func (x *GetPodResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetPodResourcesResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{1}
}

func (x *GetPodResourcesResponse) GetPodNetnsPath() string {
	if x != nil {
		return x.PodNetnsPath
	}
	return ""
}

type GetPodIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodIPsRequest) Reset() {
	*x = GetPodIPsRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodIPsRequest) ProtoMessage() {}

func (x *GetPodIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodIPsRequest.ProtoReflect.Descriptor instead.
func (*GetPodIPsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{2}
}

func (x *GetPodIPsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type PodInterfaceIPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInterfaceIPs) Reset() {
	*x = PodInterfaceIPs{}
	mi := &file_proto_pod_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInterfaceIPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInterfaceIPs) ProtoMessage() {}

func (x *PodInterfaceIPs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInterfaceIPs.ProtoReflect.Descriptor instead.
func (*PodInterfaceIPs) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{3}
}

func (x *PodInterfaceIPs) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type PodRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRoute) Reset() {
	*x = PodRoute{}
	mi := &file_proto_pod_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRoute) ProtoMessage() {}

func (x *PodRoute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRoute.ProtoReflect.Descriptor instead.
func (*PodRoute) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{4}
}

func (x *PodRoute) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PodRoute) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *PodRoute) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type GetPodIPsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	InterfaceIps  map[string]*PodInterfaceIPs `protobuf:"bytes,1,rep,name=interface_ips,json=interfaceIps,proto3" json:"interface_ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Routes        []*PodRoute                 `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodIPsResponse) Reset() {
	*x = GetPodIPsResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodIPsResponse) ProtoMessage() {}

func (x *GetPodIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodIPsResponse.ProtoReflect.Descriptor instead.
func (*GetPodIPsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{5}
}

func (x *GetPodIPsResponse) GetInterfaceIps() map[string]*PodInterfaceIPs {
	if x != nil {
		return x.InterfaceIps
	}
	return nil
}

func (x *GetPodIPsResponse) GetRoutes() []*PodRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type GetPodNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodNetworkRequest) Reset() {
	*x = GetPodNetworkRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodNetworkRequest) ProtoMessage() {}

func (x *GetPodNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetPodNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{6}
}

func (x *GetPodNetworkRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// NetworkInterface describes a single interface inside the pod netns.
type NetworkInterface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the interface (e.g. "eth0", "mlx5_0").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MAC address of the interface.
	MacAddress string `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// Device type (netdev or RDMA).
	Type DeviceType `protobuf:"varint,3,opt,name=type,proto3,enum=dranet.networking.v1.DeviceType" json:"type,omitempty"`
	// MTU of the interface.
	Mtu uint32 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Operational state (e.g. "UP", "DOWN").
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// IP addresses assigned to this interface in CIDR notation (e.g. "10.0.0.2/24").
	Addresses     []string `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_proto_pod_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_NETDEV
}

func (x *NetworkInterface) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkInterface) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NetworkInterface) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// RouteEntry describes a single route inside the pod netns.
type RouteEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination in CIDR notation (e.g. "10.0.0.0/24", "default").
	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Gateway address. Empty if directly connected.
	Gateway string `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Interface name this route is associated with.
	InterfaceName string `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// Route metric / priority.
	Metric uint32 `protobuf:"varint,4,opt,name=metric,proto3" json:"metric,omitempty"`
	// Route scope (e.g. "link", "global", "host").
	Scope         string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_proto_pod_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{8}
}

func (x *RouteEntry) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteEntry) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *RouteEntry) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *RouteEntry) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *RouteEntry) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// RoutingRule describes an ip rule entry inside the pod netns.
type RoutingRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Priority of the rule.
	Priority uint32 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	// Source prefix to match (CIDR), or empty for all.
	Src string `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// Destination prefix to match (CIDR), or empty for all.
	Dst string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	// Routing table to use (e.g. "main", "254", a custom table id).
	Table string `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	// Interface name to match on (iif or oif).
	Iif           string `protobuf:"bytes,5,opt,name=iif,proto3" json:"iif,omitempty"`
	Oif           string `protobuf:"bytes,6,opt,name=oif,proto3" json:"oif,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	mi := &file_proto_pod_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{9}
}

func (x *RoutingRule) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RoutingRule) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RoutingRule) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RoutingRule) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RoutingRule) GetIif() string {
	if x != nil {
		return x.Iif
	}
	return ""
}

func (x *RoutingRule) GetOif() string {
	if x != nil {
		return x.Oif
	}
	return ""
}

type GetPodNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All network interfaces inside the pod.
	Interfaces []*NetworkInterface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	// All routes inside the pod netns.
	Routes []*RouteEntry `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	// All routing rules (ip rules) inside the pod netns.
	Rules         []*RoutingRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodNetworkResponse) Reset() {
	*x = GetPodNetworkResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodNetworkResponse) ProtoMessage() {}

func (x *GetPodNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetPodNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{10}
}

func (x *GetPodNetworkResponse) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *GetPodNetworkResponse) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetPodNetworkResponse) GetRules() []*RoutingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type MoveDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox to move the device into.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Name of the device in the root namespace (e.g. "ens4f0", "mlx5_0").
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Type of device.
	DeviceType DeviceType `protobuf:"varint,3,opt,name=device_type,json=deviceType,proto3,enum=dranet.networking.v1.DeviceType" json:"device_type,omitempty"`
	// Optional: rename the device inside the pod netns. If empty, keeps the
	// original name.
	TargetName    string `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveDeviceRequest) Reset() {
	*x = MoveDeviceRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDeviceRequest) ProtoMessage() {}

func (x *MoveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDeviceRequest.ProtoReflect.Descriptor instead.
func (*MoveDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{11}
}

func (x *MoveDeviceRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *MoveDeviceRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *MoveDeviceRequest) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_NETDEV
}

func (x *MoveDeviceRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

type MoveDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The final name of the device inside the pod netns.
	DeviceName string `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// IP addresses that were carried over, in CIDR notation.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Routes that were carried over.
	Routes []*RouteEntry `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	// Routing rules that were carried over.
	Rules         []*RoutingRule `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveDeviceResponse) Reset() {
	*x = MoveDeviceResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDeviceResponse) ProtoMessage() {}

func (x *MoveDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDeviceResponse.ProtoReflect.Descriptor instead.
func (*MoveDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{12}
}

func (x *MoveDeviceResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *MoveDeviceResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *MoveDeviceResponse) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *MoveDeviceResponse) GetRules() []*RoutingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AssignIPAddressRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Interface name inside the pod netns.
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// IP address in CIDR notation (e.g. "10.0.0.5/24", "fd00::5/64").
	Address       string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignIPAddressRequest) Reset() {
	*x = AssignIPAddressRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignIPAddressRequest) ProtoMessage() {}

func (x *AssignIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignIPAddressRequest.ProtoReflect.Descriptor instead.
func (*AssignIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{13}
}

func (x *AssignIPAddressRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *AssignIPAddressRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *AssignIPAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AssignIPAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignIPAddressResponse) Reset() {
	*x = AssignIPAddressResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignIPAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignIPAddressResponse) ProtoMessage() {}

func (x *AssignIPAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignIPAddressResponse.ProtoReflect.Descriptor instead.
func (*AssignIPAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{14}
}

type ApplyRouteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Route to apply inside the pod netns.
	Route *RouteEntry `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	// When true, the route is applied in the host (root) network namespace
	// instead of the pod's netns. Defaults to false (pod netns).
	HostNetwork   bool `protobuf:"varint,3,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRouteRequest) Reset() {
	*x = ApplyRouteRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRouteRequest) ProtoMessage() {}

func (x *ApplyRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRouteRequest.ProtoReflect.Descriptor instead.
func (*ApplyRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyRouteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ApplyRouteRequest) GetRoute() *RouteEntry {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *ApplyRouteRequest) GetHostNetwork() bool {
	if x != nil {
		return x.HostNetwork
	}
	return false
}

type ApplyRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRouteResponse) Reset() {
	*x = ApplyRouteResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRouteResponse) ProtoMessage() {}

func (x *ApplyRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRouteResponse.ProtoReflect.Descriptor instead.
func (*ApplyRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{16}
}

type ApplyRuleRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Rule to apply inside the pod netns.
	Rule *RoutingRule `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	// When true, the rule is applied in the host (root) network namespace
	// instead of the pod's netns. Defaults to false (pod netns).
	HostNetwork   bool `protobuf:"varint,3,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRuleRequest) Reset() {
	*x = ApplyRuleRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRuleRequest) ProtoMessage() {}

func (x *ApplyRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRuleRequest.ProtoReflect.Descriptor instead.
func (*ApplyRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyRuleRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ApplyRuleRequest) GetRule() *RoutingRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *ApplyRuleRequest) GetHostNetwork() bool {
	if x != nil {
		return x.HostNetwork
	}
	return false
}

type ApplyRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRuleResponse) Reset() {
	*x = ApplyRuleResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRuleResponse) ProtoMessage() {}

func (x *ApplyRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRuleResponse.ProtoReflect.Descriptor instead.
func (*ApplyRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{18}
}

// VethConfig creates a veth pair. One end is placed inside the pod netns
// (named by the top-level `name` field), the other end stays in the root
// namespace (or is moved to an optional target netns).
type VethConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the peer end that remains in the root (or host) namespace.
	PeerName string `protobuf:"bytes,1,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	// Optional: network namespace path to place the peer end into.
	// If empty, the peer stays in the root namespace.
	PeerNetnsPath string `protobuf:"bytes,2,opt,name=peer_netns_path,json=peerNetnsPath,proto3" json:"peer_netns_path,omitempty"`
	// Optional: bridge name to attach the peer end to.
	// This is useful for connecting the veth to a bridge in the host namespace.
	PeerMaster    string `protobuf:"bytes,3,opt,name=peer_master,json=peerMaster,proto3" json:"peer_master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VethConfig) Reset() {
	*x = VethConfig{}
	mi := &file_proto_pod_network_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VethConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VethConfig) ProtoMessage() {}

func (x *VethConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VethConfig.ProtoReflect.Descriptor instead.
func (*VethConfig) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{19}
}

func (x *VethConfig) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *VethConfig) GetPeerNetnsPath() string {
	if x != nil {
		return x.PeerNetnsPath
	}
	return ""
}

func (x *VethConfig) GetPeerMaster() string {
	if x != nil {
		return x.PeerMaster
	}
	return ""
}

// VxlanConfig creates a VXLAN tunnel endpoint inside the pod netns.
type VxlanConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VXLAN Network Identifier (VNI).
	Vni uint32 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	// Multicast group or remote unicast IP for BUM traffic.
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// UDP destination port (default 4789 if unset).
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Name of the underlay (physical) device used for tunnel traffic.
	// Corresponds to `ip link add ... dev <underlay_device>`.
	UnderlayDevice string `protobuf:"bytes,4,opt,name=underlay_device,json=underlayDevice,proto3" json:"underlay_device,omitempty"`
	// Source address for outgoing packets.
	Local string `protobuf:"bytes,5,opt,name=local,proto3" json:"local,omitempty"`
	// TTL for outgoing packets. 0 means inherit.
	Ttl uint32 `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Whether to enable learning of remote MAC/IP entries.
	Learning      bool `protobuf:"varint,7,opt,name=learning,proto3" json:"learning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VxlanConfig) Reset() {
	*x = VxlanConfig{}
	mi := &file_proto_pod_network_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VxlanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VxlanConfig) ProtoMessage() {}

func (x *VxlanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VxlanConfig.ProtoReflect.Descriptor instead.
func (*VxlanConfig) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{20}
}

func (x *VxlanConfig) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *VxlanConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *VxlanConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VxlanConfig) GetUnderlayDevice() string {
	if x != nil {
		return x.UnderlayDevice
	}
	return ""
}

func (x *VxlanConfig) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *VxlanConfig) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *VxlanConfig) GetLearning() bool {
	if x != nil {
		return x.Learning
	}
	return false
}

// DummyConfig creates a dummy interface. No additional parameters needed
// beyond the common fields (name, mtu, addresses).
type DummyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyConfig) Reset() {
	*x = DummyConfig{}
	mi := &file_proto_pod_network_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyConfig) ProtoMessage() {}

func (x *DummyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyConfig.ProtoReflect.Descriptor instead.
func (*DummyConfig) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{21}
}

// IpvlanConfig creates an ipvlan subordinate device.
type IpvlanConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent (master) interface name (e.g. "eth0").
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Forwarding mode.
	Mode IpvlanMode `protobuf:"varint,2,opt,name=mode,proto3,enum=dranet.networking.v1.IpvlanMode" json:"mode,omitempty"`
	// Isolation flag.
	Flag          IpvlanFlag `protobuf:"varint,3,opt,name=flag,proto3,enum=dranet.networking.v1.IpvlanFlag" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpvlanConfig) Reset() {
	*x = IpvlanConfig{}
	mi := &file_proto_pod_network_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpvlanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpvlanConfig) ProtoMessage() {}

func (x *IpvlanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpvlanConfig.ProtoReflect.Descriptor instead.
func (*IpvlanConfig) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{22}
}

func (x *IpvlanConfig) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *IpvlanConfig) GetMode() IpvlanMode {
	if x != nil {
		return x.Mode
	}
	return IpvlanMode_IPVLAN_L2
}

func (x *IpvlanConfig) GetFlag() IpvlanFlag {
	if x != nil {
		return x.Flag
	}
	return IpvlanFlag_IPVLAN_FLAG_BRIDGE
}

// MacvlanConfig creates a macvlan subordinate device.
type MacvlanConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent (master) interface name (e.g. "eth0").
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Forwarding mode.
	Mode MacvlanMode `protobuf:"varint,2,opt,name=mode,proto3,enum=dranet.networking.v1.MacvlanMode" json:"mode,omitempty"`
	// Optional: explicit MAC address. If empty, the kernel assigns one.
	MacAddress    string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MacvlanConfig) Reset() {
	*x = MacvlanConfig{}
	mi := &file_proto_pod_network_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacvlanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacvlanConfig) ProtoMessage() {}

func (x *MacvlanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacvlanConfig.ProtoReflect.Descriptor instead.
func (*MacvlanConfig) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{23}
}

func (x *MacvlanConfig) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *MacvlanConfig) GetMode() MacvlanMode {
	if x != nil {
		return x.Mode
	}
	return MacvlanMode_MACVLAN_BRIDGE
}

func (x *MacvlanConfig) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

// BridgeConfig creates a Linux bridge device.
type BridgeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable STP (Spanning Tree Protocol). Default false.
	StpEnabled bool `protobuf:"varint,1,opt,name=stp_enabled,json=stpEnabled,proto3" json:"stp_enabled,omitempty"`
	// Enable VLAN filtering on the bridge. Default false.
	VlanFiltering bool `protobuf:"varint,2,opt,name=vlan_filtering,json=vlanFiltering,proto3" json:"vlan_filtering,omitempty"`
	// Default PVID (Port VLAN ID) for ports on this bridge. 0 means use kernel default (1).
	DefaultPvid uint32 `protobuf:"varint,3,opt,name=default_pvid,json=defaultPvid,proto3" json:"default_pvid,omitempty"`
	// Enable hairpin mode (allow traffic to return on the same port). Default false.
	HairpinMode   bool `protobuf:"varint,4,opt,name=hairpin_mode,json=hairpinMode,proto3" json:"hairpin_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeConfig) Reset() {
	*x = BridgeConfig{}
	mi := &file_proto_pod_network_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeConfig) ProtoMessage() {}

func (x *BridgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeConfig.ProtoReflect.Descriptor instead.
func (*BridgeConfig) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{24}
}

func (x *BridgeConfig) GetStpEnabled() bool {
	if x != nil {
		return x.StpEnabled
	}
	return false
}

func (x *BridgeConfig) GetVlanFiltering() bool {
	if x != nil {
		return x.VlanFiltering
	}
	return false
}

func (x *BridgeConfig) GetDefaultPvid() uint32 {
	if x != nil {
		return x.DefaultPvid
	}
	return 0
}

func (x *BridgeConfig) GetHairpinMode() bool {
	if x != nil {
		return x.HairpinMode
	}
	return false
}

type CreateNetdevRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox to create the device in.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Name of the device inside the pod netns (e.g. "eth0", "vxlan100").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional: MTU for the new device. 0 means use the kernel default.
	Mtu uint32 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Optional: IP addresses to assign immediately after creation, in CIDR
	// notation (e.g. "10.0.0.2/24", "fd00::2/64").
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// When true, the device is created in the host (root) network namespace
	// instead of the pod's netns. Useful for creating bridges and vxlan
	// tunnels that need to exist in the host namespace.
	HostNetwork bool `protobuf:"varint,5,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	// Optional: attach the created device to this bridge (set as master).
	// The bridge must already exist in the target namespace.
	Master string `protobuf:"bytes,6,opt,name=master,proto3" json:"master,omitempty"`
	// Device-type-specific configuration. Exactly one must be set.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*CreateNetdevRequest_Veth
	//	*CreateNetdevRequest_Vxlan
	//	*CreateNetdevRequest_Dummy
	//	*CreateNetdevRequest_Ipvlan
	//	*CreateNetdevRequest_Macvlan
	//	*CreateNetdevRequest_Bridge
	Config        isCreateNetdevRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetdevRequest) Reset() {
	*x = CreateNetdevRequest{}
	mi := &file_proto_pod_network_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetdevRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetdevRequest) ProtoMessage() {}

func (x *CreateNetdevRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetdevRequest.ProtoReflect.Descriptor instead.
func (*CreateNetdevRequest) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{25}
}

func (x *CreateNetdevRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateNetdevRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNetdevRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *CreateNetdevRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *CreateNetdevRequest) GetHostNetwork() bool {
	if x != nil {
		return x.HostNetwork
	}
	return false
}

func (x *CreateNetdevRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *CreateNetdevRequest) GetConfig() isCreateNetdevRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateNetdevRequest) GetVeth() *VethConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateNetdevRequest_Veth); ok {
			return x.Veth
		}
	}
	return nil
}

func (x *CreateNetdevRequest) GetVxlan() *VxlanConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateNetdevRequest_Vxlan); ok {
			return x.Vxlan
		}
	}
	return nil
}

func (x *CreateNetdevRequest) GetDummy() *DummyConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateNetdevRequest_Dummy); ok {
			return x.Dummy
		}
	}
	return nil
}

func (x *CreateNetdevRequest) GetIpvlan() *IpvlanConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateNetdevRequest_Ipvlan); ok {
			return x.Ipvlan
		}
	}
	return nil
}

func (x *CreateNetdevRequest) GetMacvlan() *MacvlanConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateNetdevRequest_Macvlan); ok {
			return x.Macvlan
		}
	}
	return nil
}

func (x *CreateNetdevRequest) GetBridge() *BridgeConfig {
	if x != nil {
		if x, ok := x.Config.(*CreateNetdevRequest_Bridge); ok {
			return x.Bridge
		}
	}
	return nil
}

type isCreateNetdevRequest_Config interface {
	isCreateNetdevRequest_Config()
}

type CreateNetdevRequest_Veth struct {
	Veth *VethConfig `protobuf:"bytes,10,opt,name=veth,proto3,oneof"`
}

type CreateNetdevRequest_Vxlan struct {
	Vxlan *VxlanConfig `protobuf:"bytes,11,opt,name=vxlan,proto3,oneof"`
}

type CreateNetdevRequest_Dummy struct {
	Dummy *DummyConfig `protobuf:"bytes,12,opt,name=dummy,proto3,oneof"`
}

type CreateNetdevRequest_Ipvlan struct {
	Ipvlan *IpvlanConfig `protobuf:"bytes,13,opt,name=ipvlan,proto3,oneof"`
}

type CreateNetdevRequest_Macvlan struct {
	Macvlan *MacvlanConfig `protobuf:"bytes,14,opt,name=macvlan,proto3,oneof"`
}

type CreateNetdevRequest_Bridge struct {
	Bridge *BridgeConfig `protobuf:"bytes,15,opt,name=bridge,proto3,oneof"`
}

func (*CreateNetdevRequest_Veth) isCreateNetdevRequest_Config() {}

func (*CreateNetdevRequest_Vxlan) isCreateNetdevRequest_Config() {}

func (*CreateNetdevRequest_Dummy) isCreateNetdevRequest_Config() {}

func (*CreateNetdevRequest_Ipvlan) isCreateNetdevRequest_Config() {}

func (*CreateNetdevRequest_Macvlan) isCreateNetdevRequest_Config() {}

func (*CreateNetdevRequest_Bridge) isCreateNetdevRequest_Config() {}

type CreateNetdevResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The final interface state after creation.
	Interface *NetworkInterface `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// For veth: the peer interface info (in whichever namespace it lives).
	PeerInterface *NetworkInterface `protobuf:"bytes,2,opt,name=peer_interface,json=peerInterface,proto3" json:"peer_interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetdevResponse) Reset() {
	*x = CreateNetdevResponse{}
	mi := &file_proto_pod_network_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetdevResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetdevResponse) ProtoMessage() {}

func (x *CreateNetdevResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pod_network_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetdevResponse.ProtoReflect.Descriptor instead.
func (*CreateNetdevResponse) Descriptor() ([]byte, []int) {
	return file_proto_pod_network_proto_rawDescGZIP(), []int{26}
}

func (x *CreateNetdevResponse) GetInterface() *NetworkInterface {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *CreateNetdevResponse) GetPeerInterface() *NetworkInterface {
	if x != nil {
		return x.PeerInterface
	}
	return nil
}

var File_proto_pod_network_proto protoreflect.FileDescriptor

const file_proto_pod_network_proto_rawDesc = "" +
	"\n" +
	"\x17proto/pod_network.proto\x12\x14dranet.networking.v1\"7\n" +
	"\x16GetPodResourcesRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"?\n" +
	"\x17GetPodResourcesResponse\x12$\n" +
	"\x0epod_netns_path\x18\x01 \x01(\tR\fpodNetnsPath\"1\n" +
	"\x10GetPodIPsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"#\n" +
	"\x0fPodInterfaceIPs\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"m\n" +
	"\bPodRoute\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\"\x93\x02\n" +
	"\x11GetPodIPsResponse\x12^\n" +
	"\rinterface_ips\x18\x01 \x03(\v29.dranet.networking.v1.GetPodIPsResponse.InterfaceIpsEntryR\finterfaceIps\x126\n" +
	"\x06routes\x18\x02 \x03(\v2\x1e.dranet.networking.v1.PodRouteR\x06routes\x1af\n" +
	"\x11InterfaceIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.dranet.networking.v1.PodInterfaceIPsR\x05value:\x028\x01\"5\n" +
	"\x14GetPodNetworkRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xc3\x01\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .dranet.networking.v1.DeviceTypeR\x04type\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\rR\x03mtu\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1c\n" +
	"\taddresses\x18\x06 \x03(\tR\taddresses\"\x9d\x01\n" +
	"\n" +
	"RouteEntry\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\rR\x06metric\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\"\x87\x01\n" +
	"\vRoutingRule\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\x12\x10\n" +
	"\x03iif\x18\x05 \x01(\tR\x03iif\x12\x10\n" +
	"\x03oif\x18\x06 \x01(\tR\x03oif\"\xd2\x01\n" +
	"\x15GetPodNetworkResponse\x12F\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2&.dranet.networking.v1.NetworkInterfaceR\n" +
	"interfaces\x128\n" +
	"\x06routes\x18\x02 \x03(\v2 .dranet.networking.v1.RouteEntryR\x06routes\x127\n" +
	"\x05rules\x18\x03 \x03(\v2!.dranet.networking.v1.RoutingRuleR\x05rules\"\xb7\x01\n" +
	"\x11MoveDeviceRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12A\n" +
	"\vdevice_type\x18\x03 \x01(\x0e2 .dranet.networking.v1.DeviceTypeR\n" +
	"deviceType\x12\x1f\n" +
	"\vtarget_name\x18\x04 \x01(\tR\n" +
	"targetName\"\xc6\x01\n" +
	"\x12MoveDeviceResponse\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x128\n" +
	"\x06routes\x18\x03 \x03(\v2 .dranet.networking.v1.RouteEntryR\x06routes\x127\n" +
	"\x05rules\x18\x04 \x03(\v2!.dranet.networking.v1.RoutingRuleR\x05rules\"x\n" +
	"\x16AssignIPAddressRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x19\n" +
	"\x17AssignIPAddressResponse\"\x8d\x01\n" +
	"\x11ApplyRouteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x126\n" +
	"\x05route\x18\x02 \x01(\v2 .dranet.networking.v1.RouteEntryR\x05route\x12!\n" +
	"\fhost_network\x18\x03 \x01(\bR\vhostNetwork\"\x14\n" +
	"\x12ApplyRouteResponse\"\x8b\x01\n" +
	"\x10ApplyRuleRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x125\n" +
	"\x04rule\x18\x02 \x01(\v2!.dranet.networking.v1.RoutingRuleR\x04rule\x12!\n" +
	"\fhost_network\x18\x03 \x01(\bR\vhostNetwork\"\x13\n" +
	"\x11ApplyRuleResponse\"r\n" +
	"\n" +
	"VethConfig\x12\x1b\n" +
	"\tpeer_name\x18\x01 \x01(\tR\bpeerName\x12&\n" +
	"\x0fpeer_netns_path\x18\x02 \x01(\tR\rpeerNetnsPath\x12\x1f\n" +
	"\vpeer_master\x18\x03 \x01(\tR\n" +
	"peerMaster\"\xb6\x01\n" +
	"\vVxlanConfig\x12\x10\n" +
	"\x03vni\x18\x01 \x01(\rR\x03vni\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12'\n" +
	"\x0funderlay_device\x18\x04 \x01(\tR\x0eunderlayDevice\x12\x14\n" +
	"\x05local\x18\x05 \x01(\tR\x05local\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\rR\x03ttl\x12\x1a\n" +
	"\blearning\x18\a \x01(\bR\blearning\"\r\n" +
	"\vDummyConfig\"\x92\x01\n" +
	"\fIpvlanConfig\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x124\n" +
	"\x04mode\x18\x02 \x01(\x0e2 .dranet.networking.v1.IpvlanModeR\x04mode\x124\n" +
	"\x04flag\x18\x03 \x01(\x0e2 .dranet.networking.v1.IpvlanFlagR\x04flag\"\x7f\n" +
	"\rMacvlanConfig\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x125\n" +
	"\x04mode\x18\x02 \x01(\x0e2!.dranet.networking.v1.MacvlanModeR\x04mode\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\"\x9c\x01\n" +
	"\fBridgeConfig\x12\x1f\n" +
	"\vstp_enabled\x18\x01 \x01(\bR\n" +
	"stpEnabled\x12%\n" +
	"\x0evlan_filtering\x18\x02 \x01(\bR\rvlanFiltering\x12!\n" +
	"\fdefault_pvid\x18\x03 \x01(\rR\vdefaultPvid\x12!\n" +
	"\fhairpin_mode\x18\x04 \x01(\bR\vhairpinMode\"\xa8\x04\n" +
	"\x13CreateNetdevRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\rR\x03mtu\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12!\n" +
	"\fhost_network\x18\x05 \x01(\bR\vhostNetwork\x12\x16\n" +
	"\x06master\x18\x06 \x01(\tR\x06master\x126\n" +
	"\x04veth\x18\n" +
	" \x01(\v2 .dranet.networking.v1.VethConfigH\x00R\x04veth\x129\n" +
	"\x05vxlan\x18\v \x01(\v2!.dranet.networking.v1.VxlanConfigH\x00R\x05vxlan\x129\n" +
	"\x05dummy\x18\f \x01(\v2!.dranet.networking.v1.DummyConfigH\x00R\x05dummy\x12<\n" +
	"\x06ipvlan\x18\r \x01(\v2\".dranet.networking.v1.IpvlanConfigH\x00R\x06ipvlan\x12?\n" +
	"\amacvlan\x18\x0e \x01(\v2#.dranet.networking.v1.MacvlanConfigH\x00R\amacvlan\x12<\n" +
	"\x06bridge\x18\x0f \x01(\v2\".dranet.networking.v1.BridgeConfigH\x00R\x06bridgeB\b\n" +
	"\x06config\"\xab\x01\n" +
	"\x14CreateNetdevResponse\x12D\n" +
	"\tinterface\x18\x01 \x01(\v2&.dranet.networking.v1.NetworkInterfaceR\tinterface\x12M\n" +
	"\x0epeer_interface\x18\x02 \x01(\v2&.dranet.networking.v1.NetworkInterfaceR\rpeerInterface*\"\n" +
	"\n" +
	"DeviceType\x12\n" +
	"\n" +
	"\x06NETDEV\x10\x00\x12\b\n" +
	"\x04RDMA\x10\x01*r\n" +
	"\vMacvlanMode\x12\x12\n" +
	"\x0eMACVLAN_BRIDGE\x10\x00\x12\x10\n" +
	"\fMACVLAN_VEPA\x10\x01\x12\x13\n" +
	"\x0fMACVLAN_PRIVATE\x10\x02\x12\x14\n" +
	"\x10MACVLAN_PASSTHRU\x10\x03\x12\x12\n" +
	"\x0eMACVLAN_SOURCE\x10\x04*:\n" +
	"\n" +
	"IpvlanMode\x12\r\n" +
	"\tIPVLAN_L2\x10\x00\x12\r\n" +
	"\tIPVLAN_L3\x10\x01\x12\x0e\n" +
	"\n" +
	"IPVLAN_L3S\x10\x02*S\n" +
	"\n" +
	"IpvlanFlag\x12\x16\n" +
	"\x12IPVLAN_FLAG_BRIDGE\x10\x00\x12\x17\n" +
	"\x13IPVLAN_FLAG_PRIVATE\x10\x01\x12\x14\n" +
	"\x10IPVLAN_FLAG_VEPA\x10\x022\xbb\x06\n" +
	"\n" +
	"PodNetwork\x12n\n" +
	"\x0fGetPodResources\x12,.dranet.networking.v1.GetPodResourcesRequest\x1a-.dranet.networking.v1.GetPodResourcesResponse\x12\\\n" +
	"\tGetPodIPs\x12&.dranet.networking.v1.GetPodIPsRequest\x1a'.dranet.networking.v1.GetPodIPsResponse\x12h\n" +
	"\rGetPodNetwork\x12*.dranet.networking.v1.GetPodNetworkRequest\x1a+.dranet.networking.v1.GetPodNetworkResponse\x12_\n" +
	"\n" +
	"MoveDevice\x12'.dranet.networking.v1.MoveDeviceRequest\x1a(.dranet.networking.v1.MoveDeviceResponse\x12n\n" +
	"\x0fAssignIPAddress\x12,.dranet.networking.v1.AssignIPAddressRequest\x1a-.dranet.networking.v1.AssignIPAddressResponse\x12_\n" +
	"\n" +
	"ApplyRoute\x12'.dranet.networking.v1.ApplyRouteRequest\x1a(.dranet.networking.v1.ApplyRouteResponse\x12\\\n" +
	"\tApplyRule\x12&.dranet.networking.v1.ApplyRuleRequest\x1a'.dranet.networking.v1.ApplyRuleResponse\x12e\n" +
	"\fCreateNetdev\x12).dranet.networking.v1.CreateNetdevRequest\x1a*.dranet.networking.v1.CreateNetdevResponseB7Z5github.com/google/dranet/api/networking/v1;networkingb\x06proto3"

var (
	file_proto_pod_network_proto_rawDescOnce sync.Once
	file_proto_pod_network_proto_rawDescData []byte
)

func file_proto_pod_network_proto_rawDescGZIP() []byte {
	file_proto_pod_network_proto_rawDescOnce.Do(func() {
		file_proto_pod_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pod_network_proto_rawDesc), len(file_proto_pod_network_proto_rawDesc)))
	})
	return file_proto_pod_network_proto_rawDescData
}

var file_proto_pod_network_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_pod_network_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_pod_network_proto_goTypes = []any{
	(DeviceType)(0),                 // 0: dranet.networking.v1.DeviceType
	(MacvlanMode)(0),                // 1: dranet.networking.v1.MacvlanMode
	(IpvlanMode)(0),                 // 2: dranet.networking.v1.IpvlanMode
	(IpvlanFlag)(0),                 // 3: dranet.networking.v1.IpvlanFlag
	(*GetPodResourcesRequest)(nil),  // 4: dranet.networking.v1.GetPodResourcesRequest
	(*GetPodResourcesResponse)(nil), // 5: dranet.networking.v1.GetPodResourcesResponse
	(*GetPodIPsRequest)(nil),        // 6: dranet.networking.v1.GetPodIPsRequest
	(*PodInterfaceIPs)(nil),         // 7: dranet.networking.v1.PodInterfaceIPs
	(*PodRoute)(nil),                // 8: dranet.networking.v1.PodRoute
	(*GetPodIPsResponse)(nil),       // 9: dranet.networking.v1.GetPodIPsResponse
	(*GetPodNetworkRequest)(nil),    // 10: dranet.networking.v1.GetPodNetworkRequest
	(*NetworkInterface)(nil),        // 11: dranet.networking.v1.NetworkInterface
	(*RouteEntry)(nil),              // 12: dranet.networking.v1.RouteEntry
	(*RoutingRule)(nil),             // 13: dranet.networking.v1.RoutingRule
	(*GetPodNetworkResponse)(nil),   // 14: dranet.networking.v1.GetPodNetworkResponse
	(*MoveDeviceRequest)(nil),       // 15: dranet.networking.v1.MoveDeviceRequest
	(*MoveDeviceResponse)(nil),      // 16: dranet.networking.v1.MoveDeviceResponse
	(*AssignIPAddressRequest)(nil),  // 17: dranet.networking.v1.AssignIPAddressRequest
	(*AssignIPAddressResponse)(nil), // 18: dranet.networking.v1.AssignIPAddressResponse
	(*ApplyRouteRequest)(nil),       // 19: dranet.networking.v1.ApplyRouteRequest
	(*ApplyRouteResponse)(nil),      // 20: dranet.networking.v1.ApplyRouteResponse
	(*ApplyRuleRequest)(nil),        // 21: dranet.networking.v1.ApplyRuleRequest
	(*ApplyRuleResponse)(nil),       // 22: dranet.networking.v1.ApplyRuleResponse
	(*VethConfig)(nil),              // 23: dranet.networking.v1.VethConfig
	(*VxlanConfig)(nil),             // 24: dranet.networking.v1.VxlanConfig
	(*DummyConfig)(nil),             // 25: dranet.networking.v1.DummyConfig
	(*IpvlanConfig)(nil),            // 26: dranet.networking.v1.IpvlanConfig
	(*MacvlanConfig)(nil),           // 27: dranet.networking.v1.MacvlanConfig
	(*BridgeConfig)(nil),            // 28: dranet.networking.v1.BridgeConfig
	(*CreateNetdevRequest)(nil),     // 29: dranet.networking.v1.CreateNetdevRequest
	(*CreateNetdevResponse)(nil),    // 30: dranet.networking.v1.CreateNetdevResponse
	nil,                             // 31: dranet.networking.v1.GetPodIPsResponse.InterfaceIpsEntry
}
var file_proto_pod_network_proto_depIdxs = []int32{
	31, // 0: dranet.networking.v1.GetPodIPsResponse.interface_ips:type_name -> dranet.networking.v1.GetPodIPsResponse.InterfaceIpsEntry
	8,  // 1: dranet.networking.v1.GetPodIPsResponse.routes:type_name -> dranet.networking.v1.PodRoute
	0,  // 2: dranet.networking.v1.NetworkInterface.type:type_name -> dranet.networking.v1.DeviceType
	11, // 3: dranet.networking.v1.GetPodNetworkResponse.interfaces:type_name -> dranet.networking.v1.NetworkInterface
	12, // 4: dranet.networking.v1.GetPodNetworkResponse.routes:type_name -> dranet.networking.v1.RouteEntry
	13, // 5: dranet.networking.v1.GetPodNetworkResponse.rules:type_name -> dranet.networking.v1.RoutingRule
	0,  // 6: dranet.networking.v1.MoveDeviceRequest.device_type:type_name -> dranet.networking.v1.DeviceType
	12, // 7: dranet.networking.v1.MoveDeviceResponse.routes:type_name -> dranet.networking.v1.RouteEntry
	13, // 8: dranet.networking.v1.MoveDeviceResponse.rules:type_name -> dranet.networking.v1.RoutingRule
	12, // 9: dranet.networking.v1.ApplyRouteRequest.route:type_name -> dranet.networking.v1.RouteEntry
	13, // 10: dranet.networking.v1.ApplyRuleRequest.rule:type_name -> dranet.networking.v1.RoutingRule
	2,  // 11: dranet.networking.v1.IpvlanConfig.mode:type_name -> dranet.networking.v1.IpvlanMode
	3,  // 12: dranet.networking.v1.IpvlanConfig.flag:type_name -> dranet.networking.v1.IpvlanFlag
	1,  // 13: dranet.networking.v1.MacvlanConfig.mode:type_name -> dranet.networking.v1.MacvlanMode
	23, // 14: dranet.networking.v1.CreateNetdevRequest.veth:type_name -> dranet.networking.v1.VethConfig
	24, // 15: dranet.networking.v1.CreateNetdevRequest.vxlan:type_name -> dranet.networking.v1.VxlanConfig
	25, // 16: dranet.networking.v1.CreateNetdevRequest.dummy:type_name -> dranet.networking.v1.DummyConfig
	26, // 17: dranet.networking.v1.CreateNetdevRequest.ipvlan:type_name -> dranet.networking.v1.IpvlanConfig
	27, // 18: dranet.networking.v1.CreateNetdevRequest.macvlan:type_name -> dranet.networking.v1.MacvlanConfig
	28, // 19: dranet.networking.v1.CreateNetdevRequest.bridge:type_name -> dranet.networking.v1.BridgeConfig
	11, // 20: dranet.networking.v1.CreateNetdevResponse.interface:type_name -> dranet.networking.v1.NetworkInterface
	11, // 21: dranet.networking.v1.CreateNetdevResponse.peer_interface:type_name -> dranet.networking.v1.NetworkInterface
	7,  // 22: dranet.networking.v1.GetPodIPsResponse.InterfaceIpsEntry.value:type_name -> dranet.networking.v1.PodInterfaceIPs
	4,  // 23: dranet.networking.v1.PodNetwork.GetPodResources:input_type -> dranet.networking.v1.GetPodResourcesRequest
	6,  // 24: dranet.networking.v1.PodNetwork.GetPodIPs:input_type -> dranet.networking.v1.GetPodIPsRequest
	10, // 25: dranet.networking.v1.PodNetwork.GetPodNetwork:input_type -> dranet.networking.v1.GetPodNetworkRequest
	15, // 26: dranet.networking.v1.PodNetwork.MoveDevice:input_type -> dranet.networking.v1.MoveDeviceRequest
	17, // 27: dranet.networking.v1.PodNetwork.AssignIPAddress:input_type -> dranet.networking.v1.AssignIPAddressRequest
	19, // 28: dranet.networking.v1.PodNetwork.ApplyRoute:input_type -> dranet.networking.v1.ApplyRouteRequest
	21, // 29: dranet.networking.v1.PodNetwork.ApplyRule:input_type -> dranet.networking.v1.ApplyRuleRequest
	29, // 30: dranet.networking.v1.PodNetwork.CreateNetdev:input_type -> dranet.networking.v1.CreateNetdevRequest
	5,  // 31: dranet.networking.v1.PodNetwork.GetPodResources:output_type -> dranet.networking.v1.GetPodResourcesResponse
	9,  // 32: dranet.networking.v1.PodNetwork.GetPodIPs:output_type -> dranet.networking.v1.GetPodIPsResponse
	14, // 33: dranet.networking.v1.PodNetwork.GetPodNetwork:output_type -> dranet.networking.v1.GetPodNetworkResponse
	16, // 34: dranet.networking.v1.PodNetwork.MoveDevice:output_type -> dranet.networking.v1.MoveDeviceResponse
	18, // 35: dranet.networking.v1.PodNetwork.AssignIPAddress:output_type -> dranet.networking.v1.AssignIPAddressResponse
	20, // 36: dranet.networking.v1.PodNetwork.ApplyRoute:output_type -> dranet.networking.v1.ApplyRouteResponse
	22, // 37: dranet.networking.v1.PodNetwork.ApplyRule:output_type -> dranet.networking.v1.ApplyRuleResponse
	30, // 38: dranet.networking.v1.PodNetwork.CreateNetdev:output_type -> dranet.networking.v1.CreateNetdevResponse
	31, // [31:39] is the sub-list for method output_type
	23, // [23:31] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_pod_network_proto_init() }
func file_proto_pod_network_proto_init() {
	if File_proto_pod_network_proto != nil {
		return
	}
	file_proto_pod_network_proto_msgTypes[25].OneofWrappers = []any{
		(*CreateNetdevRequest_Veth)(nil),
		(*CreateNetdevRequest_Vxlan)(nil),
		(*CreateNetdevRequest_Dummy)(nil),
		(*CreateNetdevRequest_Ipvlan)(nil),
		(*CreateNetdevRequest_Macvlan)(nil),
		(*CreateNetdevRequest_Bridge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pod_network_proto_rawDesc), len(file_proto_pod_network_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pod_network_proto_goTypes,
		DependencyIndexes: file_proto_pod_network_proto_depIdxs,
		EnumInfos:         file_proto_pod_network_proto_enumTypes,
		MessageInfos:      file_proto_pod_network_proto_msgTypes,
	}.Build()
	File_proto_pod_network_proto = out.File
	file_proto_pod_network_proto_goTypes = nil
	file_proto_pod_network_proto_depIdxs = nil
}
